language: go
go:
  - "1.21"
  - "1.22"
  - tip

go_import_path: github.com/danielkov/gin-helmet

script:
  - go mod download
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic
  - go vet ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
